# Generated by Django 2.2.28 on 2026-07-06 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comic_comicpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='submitter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='users.User',
            ),
        ),
    ]
