# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20260706_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='referer',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
