# Generated by Codex on 2026-07-06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_comic_referer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='tags',
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text='A comma-separated list of tags.',
                through='taggit.TaggedItem',
                to='taggit.Tag',
                verbose_name='Tags',
            ),
        ),
    ]
