# Generated by Codex on 2026-07-07

from django.db import migrations, models
import core.utils
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_images', '0002_auto_20180826_0814'),
        ('core', '0014_comic_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionPhoto',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'video',
                    models.FileField(
                        max_length=255,
                        upload_to=core.utils.motion_photo_upload_path,
                    ),
                ),
                ('video_length', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('published', models.DateTimeField(auto_now_add=True)),
                (
                    'image',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='motion_asset',
                        to='django_images.Image',
                    ),
                ),
            ],
        ),
    ]
