# Generated by Codex on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_likes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pinlike',
            index=models.Index(
                fields=['ip_hash', 'published'],
                name='core_pinlike_ip_pub_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='comiclike',
            index=models.Index(
                fields=['ip_hash', 'published'],
                name='core_comiclike_ip_pub_idx',
            ),
        ),
    ]
