# Generated by Codex on 2026-07-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_chunked_uploads'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicView',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('actor_key', models.CharField(max_length=96)),
                ('ip_hash', models.CharField(blank=True, max_length=96)),
                ('published', models.DateTimeField(auto_now_add=True)),
                (
                    'comic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='views',
                        to='core.Comic',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='users.User',
                    ),
                ),
            ],
            options={
                'unique_together': {('comic', 'actor_key')},
                'index_together': {('comic', 'actor_key')},
            },
        ),
        migrations.CreateModel(
            name='PinView',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('actor_key', models.CharField(max_length=96)),
                ('ip_hash', models.CharField(blank=True, max_length=96)),
                ('published', models.DateTimeField(auto_now_add=True)),
                (
                    'pin',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='views',
                        to='core.Pin',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='users.User',
                    ),
                ),
            ],
            options={
                'unique_together': {('pin', 'actor_key')},
                'index_together': {('pin', 'actor_key')},
            },
        ),
        migrations.AddIndex(
            model_name='comicview',
            index=models.Index(
                fields=['ip_hash', 'published'],
                name='core_comicview_ip_pub_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='pinview',
            index=models.Index(
                fields=['ip_hash', 'published'],
                name='core_pinview_ip_pub_idx',
            ),
        ),
    ]
